### ISSUE TITLE
resume game lost text on wp8

### ISSUE THREAD

**Issue by MatriQ** [cocos2d/cocos2d-x-for-xna#24]
I use cocos2d-x-for-xna on wp8 by monogame,but there is a problem：it allways lost text when game resume,i checked the vertex data,it have not any problem.

**Comment by totallyeviljake** [comment]
are you using spritefont or BMFont? Also, are you using the latest develop branch from monogame?

**Comment by totallyeviljake** [comment]
Also, there is code for Android in the source that handles this, so maybe that code needs an "|| WINDOWS8" option too - you have to "dirty" the labels to make them regenerate the textures. spritefont labels need to be regenerated when the textures are disposed during the background/foreground lifecycle event.

**Comment by MatriQ** [comment]
thank you ,i will try to regenerate the font textures
