### ISSUE TITLE
some sprite blink

### ISSUE THREAD

**Issue by MatriQ** [cocos2d/cocos2d-x-for-xna#25]
launchscene ->mainscene->others is my scene sequence,some sprite always blink in mainscene when enter the scene from launchscene or resume game or  pressd some menuitem,but the sprites are right when back mainscene from others.
help

**Comment by totallyeviljake** [comment]
what platform is this on? Are you using CCSprite or CCScale9Sprite?

I've never seen any sprites blink like you describe. Can you run the tests application on your device to see if it does the same thing?

**Comment by totallyeviljake** [comment]
Also, this project is no longer supported. There is a new project for cocos2d-XNA.

https://github.com/totallyevil/cocos2d-xna

**Comment by MatriQ** [comment]
Thank you,let me try 

齐建平
By windows phone 

-----原始邮件-----
发件人: "Jacob Anderson" notifications@github.com
发送时间: ‎2013/‎5/‎30 7:39
收件人: "cocos2d/cocos2d-x-for-xna" cocos2d-x-for-xna@noreply.github.com
抄送: "qimat" matrixdom@126.com
主题: Re: [cocos2d-x-for-xna] some sprite blink (#25)

Also, this project is no longer supported. There is a new project for cocos2d-XNA.
https://github.com/totallyevil/cocos2d-xna
